import esbuild from "esbuild";
import process from "node:process";
import fs from "node:fs";
import builtinModules from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the GitHub repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

/** @type {import("esbuild").Plugin} */
const renameCssPlugin = {
	name: "rename-css-output",
	setup(build) {
		build.onEnd(() => {
			if (fs.existsSync("main.css")) {
				fs.renameSync("main.css", "styles.css");
			}
			copyToVault();
		});
	},
};

/**
 * When OBSIDIAN_VAULT is set, copy the built plugin into that vault after
 * every build (real files: Obsidian does not reliably see symlinks).
 * `pnpm dev:link <vault>` sets up the folder and prints the env var to use.
 */
function copyToVault() {
	const vault = process.env.OBSIDIAN_VAULT;
	if (!vault) return;
	const target = `${vault}/.obsidian/plugins/obtask`;
	fs.mkdirSync(target, { recursive: true });
	for (const file of ["main.js", "styles.css", "manifest.json"]) {
		if (fs.existsSync(file)) fs.copyFileSync(file, `${target}/${file}`);
	}
	console.log(`copied plugin to ${target}`);
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules,
	],
	format: "cjs",
	target: "es2022",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	minify: prod,
	outfile: "main.js",
	plugins: [renameCssPlugin],
});

if (prod) {
	await context.rebuild();
	await context.dispose();
	process.exit(0);
} else {
	await context.watch();
}
